apiVersion: system.k8smgmt.io/v3
kind: Project
metadata:
  description: Provides namespace as a service to development teams.
  name: naas
spec:
  clusterResourceQuota:
    cpuLimits: 36000m
    memoryLimits: 68000Mi
    pods: "100"
  defaultClusterNamespaceQuota:
    cpuLimits: 4000m
    memoryLimits: 8000Mi
    pods: "10"
