apiVersion: gitops.k8smgmt.io/v3
kind: Pipeline
metadata:
  name: terraform
  project: shared-infra-team
spec:
  stages:
  - config:
      action:
        action: Plan
        refresh: true
      agents:
      - name: gke-system-sync
      provisioner: terra
      type: Terraform
    name: deploy-vm
    type: InfraProvisioner
