apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: eks-presales
  project: shared-infra-team
spec:
  base:
    name: minimal
    version: 1.28.0
  costProfile:
    name: default-cost-profile-aws
    version: version-1670237774
  customAddons:
  - name: autoscaler-addon
    version: v1
  defaultAddons:
    csiSecretStoreConfig:
      providers:
        aws: true
    enableCsiSecretStore: true
    enableMonitoring: true
  drift:
    action: Deny
    enabled: true
  placement:
    autoPublish: true
    fleetValues:
    - eks-presales
  sharing:
    enabled: true
    projects:
    - name: caas
  type: custom
  version: v2
