apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: gke-presales
  project: shared-infra-team
spec:
  base:
    name: minimal
    version: 1.27.0
  customAddons:
  - name: ingress-nginx
    version: v1
  - dependsOn:
    - ingress-nginx
    name: argocd
    version: 5.38.1
  defaultAddons:
    csiSecretStoreConfig:
      providers: {}
    enableCsiSecretStore: true
    enableMonitoring: true
    monitoring:
      helmExporter:
        customizationEnabled: true
        discovery: {}
      metricsServer:
        customizationEnabled: true
      nodeExporter:
        customizationEnabled: true
        discovery: {}
      prometheusAdapter:
        customizationEnabled: true
  drift:
    action: Notify
    enabled: true
  placement:
    autoPublish: true
    fleetValues:
    - gke-presales
  type: custom
  version: v6
