apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: alpha-stage-workload
  project: naas
spec:
  artifact:
    artifact:
      paths:
      - name: echo.yaml
      repository: alpha
      revision: stage
    type: Yaml
  namespace: alpha-stage
  placement:
    selector: rafay.dev/clusterName=shared-infra-team-gke-73-demo
