apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gke-system-sync
  namespace: default
spec:
  encryptedData:
    credentials.password: AQAFOMixWw1ddg4/xeOqSbghKCb2K2jwDgMnFK6YRM2Hy0kQQtznFpP12UfeCUfGWxY6DQ3Gm1g63J6JkYJcHvZwwH45DWvXnXi/WZ2wbg+w5rnU0Si0D2SQuJay9geyXUwKRJ2xIgsWNOpMV9qQjfwCIF3ALIFuIrOZZ3fXCmDpuqelsIFLYztwQ2rAbCSxvj25waqpwpIXhU47jKw27/iLuHSKV4o83MvH5lehnYuzp5WFqWK0Y054KI2/T/rTGP0BSQYfTtRxL5h0aHhIPlBUieeC0LYR35IZ7ZuBFuLBNixtNw54NfyFJ03QVd19Jw2J/jmMMWvaIKeay3/zzBfDUB7JV2Bu5nxC5iznL/uKsZEAcsOd1LL3/jX1BDnSm6jAhB1oNNob9kdKY6gGnmku4i8ulIxEvwFuOkUJX1Q/GYp8Q8NbS6apuVdOJ/vo1vc8OjPdJE2NTfZv2XRofDL75GS2tKtabN5XxxrJRA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gke-system-sync
      namespace: default

