apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gke-system-sync
  namespace: default
spec:
  encryptedData:
    credentials.password: AQBOLB/72HSw10LsQY7KI+yyFuf2BAUxOUiENMI132TZXtY4c+e2+1+pzqSXCJYFSnVBI5lOPF39HfVL5rt7hUEnbZB5FuYdl2dgNuDI9YFZTd8EGyltyJElqgCuTkAIDrNbMPkX1g6Akkeo5vnaasJYLYE4A4IK5yIfE+oR12js7h3XRATmV3RippuwMp78VaMUETsqiBVKzyRtqie/yeOnvSQuDvFXZUmbeNtbQ4dgubMkhjamlAPrLwX56fPvw3QUAMA0u8MNTLoDaQByVKd83FDGz8M9fLllaKefO8IXO31RlXzJAQVibS3vBUBkhW2siT/DFQx+qKrueLuUSVPD6kwOififZuA3XFynsVahboDiZsx0a0OITOZpL1U111e38fa5TKVkqHsDFgNEJOccWYh62bQcramW8RGEmarFfoxtbGtyrpuIJUN683+6tjPDHIOPdDkXxGTW/OrC4BnQPTvXE+JR8t+8VobRpw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gke-system-sync
      namespace: default

