apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gke-system-sync
  namespace: default
spec:
  encryptedData:
    credentials.password: AQBSCSP8VJ9TsH6WolyYtwDykLEe/u7BV5V9F6Wk7/cINQ7x0sJAd472oJ+sGh5oaqAfSaI2ADobbXrZMX+xDZuTz7bmsUyQhKaXFNZvAldcBOlSxnCr4gm35NZhSIcC7Ey2rCmGLqhkIlz4MblEQujjela5Q+M+X8jo+FJHezBygzZ0lgYytTOPf3wS5T1gKgz1o+QWcIRL+ChyoEMjALOpxv/SoRs0T8yJ0SU1Qaml3FbbSYTKdUTKw9OUOGeeVfrgDUPyjRxFRwejW/2VvxycPqvMTI0LLmJnUNtzdJgnFBMD+p21JadG2LFnLyC2BNPKNSL/ZgeYvpcmvc4KYI3WMAyWo9TZkzkLWFP1MiYe9/n+KbD26oLwRhWVqm7GmAr98+UjIE5jfaCLPSC5qwJ54SvD+0E/5AmJwjF3AdWGwJxPjvhIZVdSs6bfFyTvk564a7/A5LL6R/rLxmDuEA7+LqZU1qjN8SZf6ncDRw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gke-system-sync
      namespace: default

