apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gke-system-sync
  namespace: default
spec:
  encryptedData:
    credentials.password: AQAdBpOhjobvnGFRmJiMyyhu7e95vdsZ8l9fWy0MSVsFWUijTsH6vPWgUu8dNZco5uSyR/SKwQrKL3kx7A2WlfrQREObQdNQcdtKFotyjF1iXabKX9QHRzF7uWeWLzmVwH/Hwyq/MK0bp6h7EqgggrTpvVTwYozd8NQ+OLg1dZGqWEb4uTbT4RCrXtBpy+nCiozMfbSLQVIf0fnuThFBuvi27eo1meCZ3pNVOiofsyfQYXgPTq2PiojRnw7mGGnG+v7LZ6j84oupPbIsJcOa7PHQ7YcnjOCLVykPY8hUIkxDiOwObEd8STIT2eWgNIALl9Fjxp/Y8Ki0TzrmuipMJFjwpLJQSiBa3pQvmsFn6UUio8mEdPJ6yKStLXtCDJQ7gttkxocHsDgXcdlkFTaUhTuy2FStw/8fTchyGekB6mK09rKC072zxkKLFdA8bINOoLXebauVKArSyRjqGjRvGB08MT4TeyEohKs28w76Wg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gke-system-sync
      namespace: default

