apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gke-system-sync
  namespace: default
spec:
  encryptedData:
    credentials.password: AQDJQbBJMxzYQBxuhT90s11XTh0f9Q11sIIZby6ZlIfonhLzMfsXUgPNe/nKdfrojL7+DNSq2Z50uynxk9Z8ttfRwrR53K8f3R7x9sgQnegiR8OOWpgoednif6Qi1jIFO4o1+GVSH+h5qYY0qjhC88LaH2XC9M6RqhvJCIAnZVByTvOeewdVMZf7O3HUNZljWrv7VljOF/UbF0b1wGJ78sOOqzfGBkT7KNvJ6LlJILCSf9afRbxZiopSVhj1vOSryak33PMZZvoiSDgniUnHzOBS+nEQIBLhvzPZhifM6pfVVFMM0/V7RpG/fqvXPz+RZlTkjC5RaCwc+Z5tGCEA3+/M/45n7OWhKGN88kvvLi2rMZXltKV2cvKqZv9HYfAfus+cInYwzc6fFlGX5QAo4ncHnQN9wwuft0gJT9yjvgyumj7w9/a5958saahnpLMoweJYwFcX7VyjsMjRyCNT0APZt+SoYqx3SYFKqYBfsQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gke-system-sync
      namespace: default

