apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gke-system-sync
  namespace: default
spec:
  encryptedData:
    credentials.password: AQAM96oMKJd2F9H1e8uXS66oPk+Rnc6CPIlrtNrtuXNVplzC85D4CFX+OfpvosTqXZhGLqVpzi3ZzPIuNDFBkF7DDEODD/8xc0Rj9l7Vv8i4Qtd5NlSQRspfNQlj8YPvuaHv5+PwxRtWhqxytKYj8CZYQMtUyrYfwGvVv2SXKjAMBayCRXpQfrwq2u64Y3BSVAQZojyWA9kyameRGwio67dJLsA3c5WlHpLfhvsapGDrX05hVjJcNMrjKRJMakKSW5es4AVbQEFr5UJsfTGuGJOaAsv91GnW/RUqY+OfTt1UhPXFrTrhyRJDgIeAktOSZsJq+tgUXdjNdW8BT7PA8JP1+iHpGqhWhp6NElwP2xlkIQqWyr27pDdMGOF4M1Sd9nj9cE7eEwNpqxSuMQM4F5bcDe8nvz4slbZWK0Qp/xVmy65kPkgUJgbxJR3zehY8rVDNVnnhawJpf5h1Od6gCvhYw0gNbUzKVYZpCKyuGA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gke-system-sync
      namespace: default

