apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gke-system-sync
  namespace: default
spec:
  encryptedData:
    credentials.password: AQCsVJEU97hhTE8Lr79l3mlR31nqndZJIyoNsy36YrP3XTB2bit+Eg0gjmP4ExdGg/yUIZ1CMnV02JlspbN7VafTN7tcXJH6z6A4iiMpYSch0TgzE1RmrbWhOzQDH1rh1qZC4090Shn2ZGyz1Huy8JkzZUbf+Edj2h05Yg/199TMS5RcjE+MDN+B3J2aNRqbE12TJc7eXpoibPLsYdgCBNAi0VYTBICG/GXMxo6GsLJKCtqzoiP/ZlUyHYmaYiK5SsRB+VQiTOW02vAY7+x1rIUlbgno77yi8MPhnXp8DfB5z3GthJFN2RrkAQLkSKbSuhhOvX6zHAMYhEQeoODG54D6ywR8vpwUjacZJd+aQuKGk2l81x7JOiYk4EydLoFJ1yGa0zSOqs9fjhWa9+gwZ9p6RCujMI+U+eG9hpNi0Ag6xin/Z5lA873WUrXiFgKL6LR9q/D5V4XJncUsxhWlDs8DtTPC8JBuAZhhGVOfWA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gke-system-sync
      namespace: default

