apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gke-system-sync
  namespace: default
spec:
  encryptedData:
    credentials.password: AQCAHlEdv0p53RzUw8CGkt8p2qxmCjEO2dCd2DEQi2yOirWKTipVc2gMdZ5gW7t1YMz27ZTaeDT+plvCoG08B/jmfnNMFZ42LU8cQdweCiTPj99NeiS1s3r9mk9hEYvD9mEj34+Q6ExxumNHVDqy2tfx6LtBPla44zl+2tNtQoMul0P9qriUOaSvrmhky8kPvU85VlsjliUOxsqP8uj6Ax4MoSIvkhMQCHbjoSG54xNEVpmF80l3bJo8/pB8qXerM7gz1xVglWa/niCOA5iEw7mfAxPgQCKbgGR5VESh/URsDUvcerV2AJKxPlskU9BdOrUp+ED3Y2l/hLn6DZPKqkWyqaeb06VcqP06PwR6RFxyvN5gLaqFcZu/v3kzfbXLno1Kdp2loEU6LSYWyiEmH284tf6h+0xHEY4TtVYmn9U1tlBCIxoZTpO2t/VAu3DRcqtlvDfu4V2MTnF36UBaCmo6Q9ew82XGziXeLxz2iQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gke-system-sync
      namespace: default

