apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gke-system-sync
  namespace: default
spec:
  encryptedData:
    credentials.password: AQDXCWiZZifrWq4QAVnfQn1SHkXzjWBxmYYTM1i5HHNsFzMTNUZ1WGGl4YSUvhxq/iUDUAptU6pHqalrZ16qJy6C2/ZjhogufkGqJDOOfaQycFyrBXKUhPvjfRXrlkgIbhwDA5WhBQQhhtFXSFoMkn0l2k88v66EZYxX1zo4rjLmW9IUOUWhmmdLIlS4e/oGaocbZFDXSAw5+XUojeXDJaFVSdnkWG24CdGACkRqSxSn+EkfCZfP/iA3P1Fcmkbz9bcmGi+XkVQomTR1FvZJ0ErQO3jxP2Ojk7HdFAilYaPqqtFtmfkUKh3oXSIAA2Ilvc+/LGFBrqbTlUaZgbfb1qHjlTKrLqAcA0nKzGxNu9r+a3BhlJtIjmEiWcZEPqw8pHq4vHNANiBsWigGpXkWnplm5bhiTfQBIe9iZWqEGarDQql7xEEhw5/L0lGgwtbmBpe7Pi3WL/af2p7yV/6ht3A+dc5j/x0a2C2ytw+O/A==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gke-system-sync
      namespace: default

