apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gke-system-sync
  namespace: default
spec:
  encryptedData:
    credentials.password: AQCKKhr9JufAXJ9q/KP69T4Kbh1+GeKx7aZj3ZpthwBjoiXhuDcKYiw4F2ltUr0pr3LtaqA61mQ5IA24Nm3FzdNiA+gh/Tr588pWv81FuFd5q5oUc4e8oeKN/zSt5pOB+KIpbstG4C1qR564YDzjvfhLrgtmCD0zIduL9OR/jx9rx0pSmRLaJM+I1IMZFkIng6aFGju22ioBXA22K3YjLNuYqWIWPMWwMRXsHnpub35kCxS+DzTvZwQzpmKpLcY0acBSOlvmZN78Jnx8c5OSQqru6kthjMNMTpo7P46O2XveKnCd/6x8qMeuzq8/98OvpaEiYTOU8hDiXMGaE7M++oZNbxQ2OsLGVFewrrSmiLJpQwzUyRiD5Wtwnw5omvpAmp0AMK2p4LXu//n1lhI5PFcKO2x3JWscq8c3Wogjixp8fw5PvWBedRj5ivTHnztqMiBgnJmNFva5db1ms6OZbYeepJpB5DS1VQIHwEPLXQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gke-system-sync
      namespace: default

