apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gke-system-sync
  namespace: default
spec:
  encryptedData:
    credentials.password: AQAnIggqMiH/NqVqN6qZHeZFFVZAZXXmepl4tqGdrRVNii0f19wRanPXeDUtJkTMe2AKufuVYpzYWi+29y71Nmw/EwtS0qQHDDhcxFVcU5tvPX/Dx+x1ZproM0QXncYdn4e5DTDeQQCftEzz5cZ84UTu2B/y07sIHIlV0r02bdHgt08psYB3WPjYwpc4/ltrWZ4IYMIV5zhN7awB9ZkiUNE+x1/cCUdGJqqffqlZ5+2KBhvSlkBLE0jnPPDZJ1HZwL4sxbwa5SFlrUiitAiIwF4QP3JH2O/e/dDNlL37w8vTDsh6IrSYA8NeoldQ+ab0zByeoBi199wsbMC/rojTKbo3EfW+xcZurcM3HpFw46BMTB/osHSNNnhKUcNc8bfh31kYhAHqitefJUQYucgPXeMHm7W/IFpGhF97e07Ne8WArIq5S0a5FY5IgDRnK4QqlR9LttFBhVxVlifoyLX02lrmKCE9iO1NEs0hOCD5lg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gke-system-sync
      namespace: default

