apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gke-system-sync
  namespace: default
spec:
  encryptedData:
    credentials.password: AQARcqNfohBJ6yOAyvRPtMafxLHuFKUCBqTglef2T4KLJbxKtm2sriyePOKvs80Af+f+UOHVCEGleJv76uK+cdrgBDg2bT+cmXxZDEHVEyrSbGdeCOs9toPtXdcol5qa/oKg9bYkYwiLD90+p3g3MNHdM5AziNrExchVp8hJ0fih8Dl1YOaLnoV9Z2d8PW1IEpXIbgzdQ2mMWqMOC8SqRbZGGSoj14Jdni8YD3cqW7d4qg4N4+F2sNvlpIgXbjhSzRmM/dunFvCIc6+IhHbZYpIiMwEE5BnWG2mUbCab7tloq8pwcEQ3ge2lFRr6Gx3E/1jWZTQrYeE6l6niXrHVf4kjQdxh39u/vFW3cXpiwO/d0seYms2aTzYy9Pf6qLhSNhzzpzIACkFhxaOVclOEbb2JgIye/8AKeaje3Di6g4bC3nR1x3VJfmR2hqyW6ZBZZ4nk+Asw+YKSbPJ3TnmaYZJ/QFLMXhk3KU0WoqPrIw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gke-system-sync
      namespace: default

