apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gke-system-sync
  namespace: default
spec:
  encryptedData:
    credentials.password: AQCGIPckam+I9QVqnYCrsYTl9jaN+V9XmmUx0U85qiwT0FqanFqu+77gc46yPCIaKNcFTAfMe0hX6BPo7+WJ1WKoIOQ62/9SZngwON6bXWTBK7aXmT+B4cvCHI2mNNTEXdsQwHvZqk+YUf7azUry5KTqkx/TdJM9wOJKABVrvuhtHsJODxblx872xzoWWud+35N6hqeBBuNDOK1qBOd8aWGKXvaMyxicfkkuNcvdI0De9zJuWxU/XRGBnVV+wzg2D55sY8QuqrRTnQ8KaEiQqLUP2Vhm7sZt95T7wtUwXvD20rbQMlnDC54cQPyOpDM6L4h2G05yJi1dsKgtINwnr0DoOjauMCludJXVyvg0gn9ygbNr/wBIrXL6+xaCdp1w8U1ECkZhOozree2rd2RZVcqZtccIspRM5Rzfeo8fhA/TPFqjUjFheIvJgqGiSa+sPNAYor26PRVfxeCxXk+Hgu7JUoipl3sQmpn0yLN5Og==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gke-system-sync
      namespace: default

