apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gke-system-sync
  namespace: default
spec:
  encryptedData:
    credentials.password: AQCFPcETNwj5UbIoZoSMNdb/AaPJQH1xqXaX5tlyCEpLxtsgMznRzs8Muna3lc3QcF9OEDN75Fzxt2OFqqn2+/JQSL6oxCywzTWsGgI0JHgUBgatzlzWSpPwTTGFYWqdQ3wbnN7J9FJollthaV7R8308/IMA6RdCbCg8GEy8C0wapGjDkQgzoEHMQO2fvK4Q/AE0JZcOe7uQIYoH+pu/Z2p/UZzwtkSAuL/g6OxWyAgYi7n+xaLTUDCF0fvUz48JAtwZEJ/1lCaaCYOT53GBEjzXtMVQWYoUg/TvY29p2jPBGGYSQY9HVrGp5pah7o+Rs+p78QNacVMGW/mn4F6QkiQMtvohkGxKogadvYDd4DN3h7shk8XeCG+QJ0FNKzvPUquCUChurRG8SIDy9O6WoHM7c8FRSlyiZlWz7Byzh3OAfRoveCbXRvCS5NFV6Yx/PT4micOH663xTYVW9J9g+Y1kbwqMUl4on5EQYYmSyQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gke-system-sync
      namespace: default

