apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gke-system-sync
  namespace: default
spec:
  encryptedData:
    credentials.password: AQBpmXrgbO/vH4OsXVxhYcBtsvu0vnyl3A/Fr0cxOmrjodEc56forw7U4T7wQDrKozOJdE67x3mv54y1caU1k5zRTa/2RZoiLk6AeHlgl58BN9AxbI7YExYTfvbvaDCrODnur50LzVujzoiwI8r05cAL8eZQPx2GbxY3i219wMojVOuAApfvsFBLqeDXuslMXXKd5cZrqiALb2py69cWr9Sn5ajycKlc88uUJw2Y/iO/6luRaaztHxA8ZUMwC9rAda4GG1qE9MfIHqlhOhpuLNWwBm7XHfNE/bKtnumroi+KbxYnhX0q0fhnMBMZ/ULA5LyFKFpMS4gwVNaaOqTHslnKvKNy5wgRHPVXchS8MrNj6Wi/4aV72rCaNfweQO9WThX1T37APpBXWUdZppxuX21RY5H+D1HN5Vj7Mf6JNqDWEGla8nsddRH/hnXCTLZeMJ0v2TpNI09dLWONWZdcYndGIiQihNsd+qNlLW6GWQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gke-system-sync
      namespace: default

