apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gke-system-sync
  namespace: default
spec:
  encryptedData:
    credentials.password: AQCWfjLtE1AWkUIrnw9fSS/SinYd/SPwu4hxjEAvJG5sgy3/wSQpYS1UT0jp/SUdTl5K+e71DAISutTLdWNr5kmitMTLdch0gjsscBs4vi6sJ3K5wdzcTbYuMfHh0/GtmKzmaW7j6yWeNlG7R6Pk0bmAqDvqs7JwjBzqTe9hVZt62gji9GPMTDHl4kZR1YE+S29v5fQHnOaQ3kjc3Vl0F/VJtzuWtJojob5MAbgJ0lytLoVtlPNeWKe/LlKfboxbQUykNNqbKpRaA8hc7XBEmWNzg1CmnGg24V6I1ZVI4zl44ual92DXJf8LI5impalWfUQcdwPcwZZBDuNhTZGJVjN7PgpafPfGxC9WnBQzK066cnKD4SU6BwmaUURpAwVdV4lCjug1R9Agdkg/BCeA3zJUxuXzSppSTeaB0oJEaRfuPe+QADH2amDjRJ9jbE0iHl6nQjBJcGDpophxKJ2N59TenajQXRhvRwxn0aOdsw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gke-system-sync
      namespace: default

