apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gke-system-sync
  namespace: default
spec:
  encryptedData:
    credentials.password: AQCypXQsMJnYY7GEy/j5ahUBoFxB8vauSqN20fkqo0GTUb3PeeuMC1wTcVt+joo/QC5xWubQ5VEHjg1gTeBIFDSMjFJIBM3ygMNT4iCd2AhpldpkiAtVuFedOyZ9IxyBJmlg5wHttj6FHoegoAGBzQrgdX8fxcgIiAlyXWNqsYUpfHHXY6ZFCUhB+tKdbfv12860J5mFBzeKa5CdzBPjO4Y6cKeQ4ILfN/KwbtOLOinBrk2n7p6AKbRs01qGW+178B+hI9wJuXMrN7ExKxF/FPd6F1YsGVlzYaDSBP6SGpQxtAW92Uc1XMvwIktsyPhYbjN0mRqCJZMcclQw7GYZLYq8hlZqrPWZ9Lkl9m8KtGy8aArqQ6PNKD4hTKVSzBs3rUGyG+8Vx64nzb+dhRe+N1LcJo1GHUGazOUFydSdT/Ad79n715kWCbsvR1Kn1xDzMyNr/Yxs6G+ux5aAq/GCOZ/OY3cNEOpqu1/R1YJKVw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gke-system-sync
      namespace: default

