apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gke-system-sync
  namespace: default
spec:
  encryptedData:
    credentials.password: AQCkoxefdgdY9qxFeieL0bEJTNtFR/C50/KkpqfAth+A+A+26LAAY2UvipJYsQdSdnQKvfA/IavY14PgFayxBpo/y/xXw8dh1MPanihkzvuSUVMMXCi4Hj00tQP2zdHSd8y02b8ZJ2j3/kryd1y9XMzSbLZ/ik6YX0rKNaLDmjp7EkWtCsKUiwUOYSAk3lp7cT2YWSrpQP6ABcYs6yOQ6r1/nJoUFc94bxwqG4N+jdjq8Ui7+ihshNGfZJkp8iXTICEGnpzXcZcwSSttJsTGjmT/cITTONTMcBVwAtEUGkwWHmuUhciud4aToJGtsYe6V3QeXb/ipiatTqJhseFAbMr1RP0xqBUUT1IiRd5e2bYIOdO6a6W/NEJxZGl49/Cn9tvtToeCQAjmh9Wu+3WiePR9biDy9THB4m/GrV1YV3s8HlGZ9kXbqvEoCmt2T+/UUxLp6tmlVztoXN23sERSY7bMuH4Goe1OpUzZ7lvl6Q==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gke-system-sync
      namespace: default

