apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gke-system-sync
  namespace: default
spec:
  encryptedData:
    credentials.password: AQBB7eoBXNl526Lr4R25kt/tqVpVruJgMM3c3bSTdOc7WZnVd1iJtEi21WgQAOA6qoUl/I5NMdr/VcEl4e10VvvIpUGgdAZb7rHo0iPhqZ8GafLw/8U14y48Q2IRRki8Z+YGcY97OvA3lSG722FJzfqLRBsX+Hcicz7UxliBNZfXTvjK3qPseerM+CgLdOiOwJCszT3heDxdhiHXJyY94Fw9i2D34Gg7zbfioLGz+L4FWLuga9f0TyLrADUlJ3ETQGjeQDK0vDAyBz5J7OLz6Dr7XfKclzHmvUTcEKR7IB19n7YejZVpWT2jOtN+n/JGcqAx5WU6LM+yxRon9AhqHnq05QnltjgEeTqMoutPiXLsAkjybRQr3S34xKfGnDoaCoPS8rsCxZoH62AKIKTmiBXEhh1KxTbRWO5KbxzZcxeR6axgpItaVkfdIz5wSti61zMQAy+ZuMBHdE1u/LUEmnmks/jTqaMncJx1cFZORw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gke-system-sync
      namespace: default

