apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gke-system-sync
  namespace: default
spec:
  encryptedData:
    credentials.password: AQBjNPkaP+AwigJTdNHrw2CDsfeMxvFgHZYBbAGqSYc/tk6omdNkt1oiVmY4zpzUopLndugIBQG5SZ9lHYF0dOmYbeYINcIPz3EJDoofbHfPpgWwRub6my/7njrCJdXx/+V/+U+ZAdAiSa+VA2mE6nkbl+ySVtK7V4lRcH4UpH7UpeGz/i3irH/2qZhoxE7vdDO7lsZ1HkFW6mHeASxk5tbdjc2gjEUBxO7py6E+IOLDJZxiDRjHQvH7MtrN+4NE7Ih1FVNEkalxMT20vLuKpzUBsHbrI6VahNwutyvl18AtPaWC1gJdRtKUBa917DVhJkxaMtKapZ+BAvNpjG5FBty0gZyvq666DiGzBogJK8IKBeJsZtoMlE0g0piNifN34LbtbGaPHFsS+OVFmBpPxQQHpp2h/5k7uGmcqdE5lm7AA03+lXgwzgaQ7VhCZt96A57s28H90DRZjooF3jnkIMUJTgyYkeSCiA7m5mJvEQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gke-system-sync
      namespace: default

