apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gke-system-sync
  namespace: default
spec:
  encryptedData:
    credentials.password: AQBOKymmF4YkoHvMkYZPy4B73EhU7mxveJJxMSb0OT7y3bx47KbQD4cMRJ+zL1XQ2l5/ymqt+/P4TA/NbtQJY2/4/O/H8jMFU8Fk7n9meuVYpSykFxnsjrIWAGbhXHT3e6KXiKtkwnI+mStJblW+uSloGYTRYeAhPgZ4RU7BgfDo3SybVvTx10wdsPFUowDCVSHRh+PpEhaSRh9RzchtjXlbKEmoUYVAI5qSY6MMA5M5IuHoNUfv2/FVfIh9Z/1Wn+7im4Ze4V3g7l/2VwHt5QErVoTz9bvvd00MKE+PMWL1MztVHwW4hnZsquJlTtkc0amzUPrO81OPdd+ZtcIibAO1zs8bozMlFb0/FvkLI2/bNiJKUbm//q7zEkOvITNhmUY3xDBXnNK1OPmMKGZueRq8jd7XCvrnlH+hRERIjldYZjaF4GOiAw2bsj5nnQQD46UJUdUCeBBShIGXih/YW6X8wCqclB1eCrXT19HNcA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gke-system-sync
      namespace: default

