apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gke-system-sync
  namespace: default
spec:
  encryptedData:
    credentials.password: AQBOwF5sAYMap4un4uC9fDprDM4vh/C+bbrfoPpTZj8FqcwZNdIQhuuDJg93NIl5vWcEPlVL5V3wfJIk9hEyma5/CX+ktVBch3xyVxJw7ng+aGwDfbJRumZwmYW3DtBuuA8tWyfadpH5XUL2RO5Lo11ULjC2vadGg6bY1/VM3GHp0sjV3L3ogsqjbwiIkWBZ8u8lOvq/Ss3JWWJJ/LfCO8fCUus/oO0vSBHm29GVna4WSD34FcoyCbr1o+LIL9EKSoo8qQkrc/Lmxn4i/XLePyyYQM0i42P/x7DbF4XAYE4y0cPzRY+ciLxA4whZKerxMREXHcGvpF20F/k4SNU6mrCn3tX+23WyqsvcOog6KLqvWUjnMLpQ3jy58prfqDcwdNVsdiF9Rj8lQokpQ75UtSCmMhMDqHkkHqQA0JtPptCl6OJ96lr6GU6kIW1J46iowlCFeVf/5e4lJSPykfzh15BxpbnndN2t147aTUeRfg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gke-system-sync
      namespace: default

