apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gke-system-sync
  namespace: default
spec:
  encryptedData:
    credentials.password: AQBkH1TR/qUOfX6zCHDdTAu9ZYJTWOruYwycqMnzD+kTdkzHDaBoxTRRZMJUkoNlkH4CBFymXetg5gvXiPkeqTHOqQnYv6GfoNLTS1eM7rai+ZkzTp+zkLx1xk5UXCXaapZ3iE4VM7ki/zjxGwCr4jUYuq+byadkR0CzugyO4GaHdUz85GfvDchHjEoOd0lBVwb9ie7vZ8+K2FVaxAP4q621+ULTeh+VU+CJAmy6g05lP8Pix83/EYAN2KTHSIDn5T3gllyYaszsQGDG2xe2sXpCIR7MzqXGnqrw4nFCm60vX/5u/r4ZBZHqLOcrguyDlpn3j7DjZCc/xBrqqfmmJjZ/mHibRfl932V+cIO6DE3NqKyu8vkBqBo4XH1QnzWQjvTwpY1kwWYVRcHrYsjB5Jg2LuB7Qp18X9mlIRaS7sI90lQDfqmeMvrB8E9VW65FFUP7IPO97r3s7xEwwGMZWVguo2k7rnpHB6nP6DMnOw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gke-system-sync
      namespace: default

