apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gke-system-sync
  namespace: default
spec:
  encryptedData:
    credentials.password: AQB62jEPh4BNcgD68sZlBfzj11LnbCiAXrPClkVZF/FT1RO9ZcpwaNCcJQGvk3/J/zPmZjT/z6HlLEVb0nGwTSzBGRaUOA+IGtkp1lSw4Z/zFHh11Obunpj4jhpLUArk4ukcZxepsDJ6jYXWL3wegU1uCk4Vtbe06Gst+M1XfmvSKQnBin7+dRzHLSVNsQeMW/Cn+02ctaoU3L1CdQMUQ0ylZGf7aWmH0YT02+v9E4DCBbVB6/FU/fNEBQDRXytgH5LCzQl+h2d7N9Z1xziGCSyYN3Eyz0QsHAZL6m0Lo0pgftxYmrjBJaxnQzDmP638R01Zm221vRylbpre2vq7JI0JK4m4zf2bvkDTccS8X77GX6rGHJb8Dm8dfsniTPNGxUfFmp28VOPg6XqWxStJsau8MyYEvxFUWpgBKxP5lHCAJrRXe0f2CL9CthTyadn8AwiqvFDpXWuEoDZMEnfxrkiUbeVvRyJxMZVztDdJpw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gke-system-sync
      namespace: default

