apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gke-system-sync
  namespace: default
spec:
  encryptedData:
    credentials.password: AQBLq6fYsuPnN8NochYRF3cNfyB0VqxTdSZ6lOyZpMWTaaCKIqQ1h/VN7a9BJLNJPyXypydeqZsRu7uyfHoDKj6EGYhh0F7jjrEIzV83yCQuk20cG4L/pR2CMb3TcvDkOUk72e4J+lM45FCK86ZSQTrT6zdf37/Xe7Ptwm3LDQfzY8JDvLMz6Rqgo5Bsn3ewgKboR1CGF6jWFHqOhNx9nEw5F7uS/i2VYRP4yAjpaacIfixggssjkpilCyZb36CmBlsnbLqtk6Q8kg/wg2YSBjrFboyZK3j2zUSIr9vJqp7/XnCpqq7sOJ0jkQIS2dRWpAG8VSGlPt1LvXv0plwuBiftvTBEF4wKSdXeYJiES5IQLqstJmnSClwUa4df+LSD5mtmCnRcjw7gQBru8NzEFaXEr7rMBXqMD4IfJKhJj5jI3HoD5i5jJgbAUfc4d6lo5ZqisdsMOCTxPLOm9lTOFTozArC6NPDVm78F9It+Aw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gke-system-sync
      namespace: default

