apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gke-system-sync
  namespace: default
spec:
  encryptedData:
    credentials.password: AQAE1QJgmlzTk4LHfUkKvxpWS+V7WCf7a6b7JmQSrwoTjNE5HrHbh9kVv9CeFQDDsT/2HP7p8omSw2HgieWlTyyoz/wI2Iygq7kCDOxJwgcRecPWvRt/TFB8IyEyAklml1h1ot9RclRvjg722IRLXj+4LyVkEPZeflCiE0cSM76LrTkc3Hy27mBa80L9DlqH2WyADLKF8GYL5vO3+T5mzZyYXfskJer9Np8v20xR5GxEGaIrkzmT+wfJcjF+93SMZnlEs/Dttrqr1XRRSa3WpvM10UrMa5Wup4AGlpje5wKc1Hf5/yGZHfJRjSyzPJKMSLfANMoMp3QCJWvDZiSlQ8KZXCL2pkWGqXVImnKzLYf3aSbpSSG+EzG+7pHJ2VP26g5Q4Rht7OmWwUlax/ppx2HvbaUBI/to/zpu5qqdTDze+69X3XtrdpVK65+xb5q213KnfY2fSTs0rSoJZQKIHna9vyid1D+3dNxkpPVTVw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gke-system-sync
      namespace: default

