apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gke-system-sync
  namespace: default
spec:
  encryptedData:
    credentials.password: AQAaGRzCuY7dsiFBB1i6Mwt/U9gkXwfb7AqYrRbfFeD2c+RFL3n1PejWbCUgm5fPrpMK7MvuN6oZBFD50QZ6Ig+48LVGT7t01HQvSWIL+wj78uky3mF9w9n8GKPeOhe18uFe7/4zzWY0cmekUf7Ux3vyPXEVrg3ww3vqv4nTyaT+SGrrM2zaY/Hi/524ZVN1WUDLxExW13Db/XNNejnnC+xeEOeBcHaC2jQIY505PHnQILPj9mMZMPBGQxEprBDr+QfctaMsm8Y19YUrU4PD8D8X0jaN1sXms2mXr/XiNvs1Sc9IA+7Mt2iLH+g0k4M5LrTkPtguYfXktyTHNy/Z65D1QcKBePSgJTPNW/BTCux86rpZBA9XkQgbyaEvPuhPYBJmi+ayw7L8fysk7J+kfQGqK7esJmeZWUYncOxwDKCxhL6/BbUEL17ku82cxq0c7RCDrLI3OvR2++Xa5qB1kgjalvuqQWGTkpTGt54B5g==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gke-system-sync
      namespace: default

