apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gke-system-sync
  namespace: default
spec:
  encryptedData:
    credentials.password: AQDM1iEz7Wp9e9QA2iJpsyJAhzyeUbnTT2WPoykpveaXUwrup37KH2zAgw2ocVfVMEyj+G41nnVx+RCF85fQKPuWUqVZ0P8qv7w0oLXijp7+JJIsWtEkU1WALVxy4Dm0L4vo4Rlnw98ys06hGdJlt94U7wt3SbIpeKARn+7ME9SxMQk0pUceGjrxmSIa5+p4tcCtoH2IDiJmPIY+qX+4RlNMFKZ0nfE5jHfqEXM18LCu0/uBvd6Cbp5mCgdpL2as3wvjL6roPhRR9FalIIXArGmJfXFZRcAS2m0Js/iwSEAeoABCSFUSComclV1a9fkxDKJtv4IuPnhx9OJ1Lv3ydxVaMdmqidljYHJYsNckXMYBwx+zwBuoErT3xALJg2vX/JhejjO/zC38WwQfo9FrLWIWk64zeynqul2DyGy+X1YVju+v8SGIH2zZ81nDfqHpwTzgnwApg/PzF9+7y4+s8+RibTXVklEO8hRStpQNSg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gke-system-sync
      namespace: default

