apiVersion: gitops.k8smgmt.io/v3
kind: Pipeline
metadata:
  name: alpha-stage-pipeline
  project: naas
spec:
  active: true
  stages:
  - config:
      useRevisionFromWebhookTriggerEvent: true
      workload: alpha-stage-workload
    name: deploy-echo-app
    type: DeployWorkload
  triggers:
  - config:
      repo:
        paths:
        - name: echo.yaml
        provider: Github
        repository: alpha
        revision: stage
    name: alpha-stage-webhook
    type: Webhook
