apiVersion: gitops.k8smgmt.io/v3
kind: Pipeline
metadata:
  name: bravo-dev-pipeline
  project: naas
spec:
  active: true
  stages:
  - config:
      useRevisionFromWebhookTriggerEvent: true
      workload: bravo-dev-workload
    name: deploy-echo-app
    type: DeployWorkload
  triggers:
  - config:
      repo:
        paths:
        - name: echo.yaml
        provider: Github
        repository: bravo
        revision: dev
    name: bravo-dev-webhook
    type: Webhook
