apiVersion: gitops.k8smgmt.io/v3
kind: Pipeline
metadata:
  name: delta-dev-pipeline
  project: naas
spec:
  active: true
  stages:
  - config:
      useRevisionFromWebhookTriggerEvent: true
      workload: delta-dev-workload
    name: deploy-echo-app
    type: DeployWorkload
  triggers:
  - config:
      repo:
        paths:
        - name: echo.yaml
        provider: Github
        repository: delta
        revision: dev
    name: delta-dev-webhook
    type: Webhook
