apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  annotations:
    rafay.dev/description: ""
  labels:
    shared-gateway-access: "true"
  name: bravo-stage
  project: naas
spec:
  limitRange:
    container: {}
    pod:
      max:
        cpu: 1u
        memory: 1999634432u
      min:
        cpu: 1u
        memory: 200278016u
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: shared-infra-team-gke-73-demo
  resourceQuotas:
    cpuLimits: 4000m
    memoryLimits: 8000Mi
    pods: "20"
    services: "10"
    storageRequests: 100Gi
