apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: argocd-echo-team-app
  project: shared-infra-team
spec:
  artifact:
    artifact:
      paths:
      - name: echo/argocd/echo-team-app.yaml
      repository: demo-apps
      revision: main
    type: Yaml
  namespace: argocd
